-- MySQL Script generated by MySQL Workbench
-- Thu 29 Jun 2017 08:51:15 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mp_playout
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mp_playout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mp_playout` DEFAULT CHARACTER SET utf8 ;
USE `mp_playout` ;

-- -----------------------------------------------------
-- Table `mp_playout`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`Media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duration` VARCHAR(45) NULL,
  `name` VARCHAR(255) NOT NULL,
  `frameRate` INT NULL,
  `path` VARCHAR(255) NOT NULL,
  `frameCount` INT NULL,
  `description` TEXT NULL,
  `resolution` VARCHAR(45) NULL,
  `provider` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`Thumbnail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`Thumbnail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mediaId` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `mediaId_idx` (`mediaId` ASC),
  CONSTRAINT `FK_Thumbnail_mediaId_Media_id`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mp_playout`.`Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`MediaInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`MediaInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mediaId` INT NULL,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_MediaInfo_mediaId_Media_id_idx` (`mediaId` ASC),
  CONSTRAINT `FK_MediaInfo_mediaId_Media_id`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mp_playout`.`Media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`Filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`Filter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`Piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`Piece` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mediaId` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `resolution` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  `filterId` INT NULL,
  `path` VARCHAR(255) NOT NULL,
  `frameCount` INT NOT NULL,
  `frameRate` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `mediaId_idx` (`mediaId` ASC),
  INDEX `FK_Piece_filterId_Filter_id_idx` (`filterId` ASC),
  CONSTRAINT `FK_Piece_mediaId_Media_id`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mp_playout`.`Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Piece_filterId_Filter_id`
    FOREIGN KEY (`filterId`)
    REFERENCES `mp_playout`.`Filter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`Playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`PlaylistPieces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`PlaylistPieces` (
  `index` INT NOT NULL AUTO_INCREMENT,
  `playlistId` INT NOT NULL,
  `pieceId` INT NULL,
  PRIMARY KEY (`index`, `playlistId`),
  INDEX `playlistId_idx` (`playlistId` ASC),
  INDEX `pieceId_idx` (`pieceId` ASC),
  CONSTRAINT `FK_PlaylistPieces_playlistId_Playlist_id`
    FOREIGN KEY (`playlistId`)
    REFERENCES `mp_playout`.`Playlist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PlaylistPieces_pieceId_Piece_id`
    FOREIGN KEY (`pieceId`)
    REFERENCES `mp_playout`.`Piece` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`Occurrence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`Occurrence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlistId` INT NULL,
  `pieceId` INT NULL,
  `startDateTime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `playlistId_idx` (`playlistId` ASC),
  INDEX `fk_Occurrence_pieceId_Piece_id_idx` (`pieceId` ASC),
  CONSTRAINT `FK_Occurrence_playlistId_Playlist_id`
    FOREIGN KEY (`playlistId`)
    REFERENCES `mp_playout`.`Playlist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Occurrence_pieceId_Piece_id`
    FOREIGN KEY (`pieceId`)
    REFERENCES `mp_playout`.`Piece` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mp_playout`.`FilterArgs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mp_playout`.`FilterArgs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filterId` INT NULL,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_FilterArgs_1_idx` (`filterId` ASC),
  CONSTRAINT `fk_FilterArgs_filterId_Filter_id`
    FOREIGN KEY (`filterId`)
    REFERENCES `mp_playout`.`Filter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table structure for table `TagPieces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TagPieces`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `TagPieces` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tagId` int(11) NOT NULL,
  `pieceId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_TagPieces_1_idx` (`tagId`),
  CONSTRAINT `fk_TagPieces_1` FOREIGN KEY (`tagId`) REFERENCES `Tags` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

-- -----------------------------------------------------
-- Table structure for table `TagPlaylists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TagPlaylists`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `TagPlaylists` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tagId` int(11) NOT NULL,
  `playlistId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_TagPlaylists_1_idx` (`tagId`),
  CONSTRAINT `fk_TagPlaylists_1` FOREIGN KEY (`tagId`) REFERENCES `Tags` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

-- -----------------------------------------------------
-- Table structure for table `Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tags`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Tags` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tag` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
